sprint-2/step-1
buckster12/stellar-burger pull request #2
Opened 2022-07-02 17:56 UTC by buckster12

2022-07-02 20:04 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.js
> +            method: 'POST',
Надо исправить: булка должна передаваться в запрос с 2 сторон

```js

ingredients // ["C7", "C5", "C4", "C7"]
```

2022-07-02 20:05 UTC, kyzinatra commented on src/components/app/app.js
>                      });
Можно лучше: мне кажется, что если вынести запросы в отдельные файлы, то это упростить `app.js`, а в самом компоненте делать только присвоение

2022-07-02 20:07 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.js
Можно лучше: Константы лучше вынести в отдельный файл

2022-07-02 20:08 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- bun должно передаваться в запрос с обоих сторон

Можно лучше:

- Папку `context` лучше переместить в `src`
- `data.json` больше не используется так что его можно удалить

Что понравилось:

- Хорошая реализация контекста
- Верно использованы хуки

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-07-03 08:07 UTC, buckster12 commented
Не уверен, что все сделал правильно, но постарался пройтись по всем пунктам.
Запрос вынес в отдельный файл, но кода получилось может еще и больше (суммарно в двух файлах); еще вынес рандомайзер ингредиентов в файл, теперь app.js смотрится чуть чище, действительно.

BUN: Пришлось убрать отдельную корзину для булок, теперь все находиться в mainBasket. Булки добавляются в начало и конец массива, и потом жестко вытаскиваются  ([0] [lastIndex]) для отрисовки. Думаю что это не самое хорошее решение, но наверняка логика еще будет меняться когда добавиться перетаскивание и Redux.

2022-07-03 08:13 UTC, kyzinatra commented
> Не уверен, что все сделал правильно, но постарался пройтись по всем пунктам. Запрос вынес в отдельный файл, но кода получилось может еще и больше (суммарно в двух файлах); еще вынес рандомайзер ингредиентов в файл, теперь app.js смотрится чуть чище, действительно.
> 
> BUN: Пришлось убрать отдельную корзину для булок, теперь все находиться в mainBasket. Булки добавляются в начало и конец массива, и потом жестко вытаскиваются ([0] [lastIndex]) для отрисовки. Думаю что это не самое хорошее решение, но наверняка логика еще будет меняться когда добавиться перетаскивание и Redux.

Да, вы правы, когда будет redux все это будет понятнее так что пока можно оставить так. Через часик просмотою все остальное и дам фидбэк

2022-07-03 09:48 UTC, kyzinatra commented
Вы отлично потрудились. Ваша работа принята. Замечу еще, что не обязательно под каждый запрос делать отдельный файл. Пока их не так много можно просто создать файл api, а если их очень много, что структуру вроде

api/
    order/
        order.js
    ingredients/
        ingredients.js

2022-07-05 09:26 UTC, merged