Sprint 5
buckster12/stellar-burger pull request #6
Opened 2022-11-21 10:21 UTC by buckster12

Постарался реализовать все что указано в задании.
Надеюсь ничего не пропустил в спешке. :)

Возможно где-то не до конца проведена типизация...

спасибо!

2022-11-21 16:05 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали большую работу по добавлению ленты заказов в ваш проект, необходимый функционал практически полностью реализован, код не содержит лишнего, вёрстка хорошая, для преобразования даты использована проверенная библиотека, так держать 👍 

Однако для успешной сдачи данной работы вам следует внимательно ознакомиться с комментариями, описанными в рамках ревью и провести необходимые корректировки, обратив особое внимание на следующие моменты:

- При **прямом** переходе на маршрут с информацией о заказах в личном кабинете `/profile/orders/:id` страница заказа открывается, но информация отсутствует (не прогружаются данные, см. https://disk.yandex.ru/i/Y0kD871D6R-tGg);
- Если открыть ленту заказов или историю заказов в личном кабинете, а потом сразу перейти на другой экран, то проект падает с ошибкой (см. https://disk.yandex.ru/i/m1MpnU-OOC4M0g);
- Следует центрировать иконку валюты относительно цены ингредиента в окне заказа (см. https://disk.yandex.ru/i/JTlp3XnGMA4SfQ);
- Следует поправить отступы на экране ленты заказа согласно дизайну (см. https://disk.yandex.ru/i/TY9DPHlL3u6_qg);
- Иконка активной вкладки в хедере должна также подсвечиваться, как и текст, согласно дизайну (см. https://disk.yandex.ru/i/5wpU_-Cj24b7hQ);
- Следует центрировать поля в форме логина, согласно дизайну ( см. https://disk.yandex.ru/i/k4NtdxLbLhtDWw);
- Если перейти из истории заказов в личном кабинете -> на ленту заказов, то:
  - Cокет закрывается сразу и лента не обновляется (закрытие одного сокета влияет на закрытие второго, см. https://disk.yandex.ru/i/3c9eeCFEFS_ppg);
  - В ленте заказов отображаются заказы пользователя, а не все заказы, следует очищать стор с заказами;
- Не следует импортировать и использовать `useDispatch` и `useSelector` (в вашем случае вы указываете тип стейта напрямую, но при расширении проекта такой подход сложнее контролировать) напрямую из react-redux, они не типизированы и за счёт any, отключают возможности `TS` по проверке, правильно ли вы передали название/функцию экшены, тот ли `payload` вы задали (см. https://redux.js.org/usage/usage-with-typescript);
- Следует добавить типизацию ко всем вашим экшенам в сторе, в неописанном виде они имеют тип `any`, который не позволяет `TS` произвести проверку;
- В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе;
- Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс;


Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Имеет смысл привести цвет прогресс-бара к дизайну, т.к. сейчас он темный и слабо различим на темном фоне проекта; 

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-21 16:05 UTC, randomroot commented on src/components/feed-list-order/feed-list-order.tsx
> +const FeedListOrder = ({date, name, ingredients, orderNumber, orderStatus}: TOrderProps) => {
🟡 **Можно улучшить:**

Типизацию компонентов лучше обозначать через интерфейс `FC<...>`:

```js
const FeedListOrder: FC<TOrderProps> = ({ ... }) =>
```

2022-11-21 16:05 UTC, randomroot commented on src/components/feed-order-page/feed-order-page.tsx
> +    const dispatch = useDispatch<any>();
🔴 **Нужно исправить:**

Не следует импортировать и использовать `useDispatch`  и `useSelector` (в вашем случае вы указываете тип стейта напрямую, но при расширении проекта такой подход сложнее контролировать) напрямую из `react-redux`, они не типизированы и за счёт `any`, отключают возможности **TS** по проверке, правильно ли вы передали название/функцию экшены, тот ли `payload` вы задали.

Чтобы исправить данную ситуацию вам необходимо создать отдельные константы, которые типизируют данные хуки (внимательно изучите документацию здесь: https://redux.js.org/usage/usage-with-typescript).

Важно типизировать с учетом использования `thunk` в проекте.

2022-11-21 16:05 UTC, randomroot commented on src/components/feed-order-page/feed-order-page.tsx
> +                <div className={`text text_type_digits-default`} style={{marginLeft: "auto", paddingRight: "10px"}}>
🔴 **Нужно исправить:**

**Здесь и далее по коду:** Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-21 16:05 UTC, randomroot commented on src/components/feed-order-page/feed-order-page.tsx
> +        } else return () => {
🟡 **Можно улучшить:**

Необязательно возвращать пустую функцию, можно просто ничего не возвращать :)

2022-11-21 16:05 UTC, randomroot commented on src/services/socketMiddleware.ts
> +                }
🔴 **Нужно исправить:**

После закрытия сокета следует сразу вызвать `next(action)`, т.к. иначе у вас переменная `socket` переходит в `null` и дальнейшее присвоение методов вызывает ошибку из-за которой приложение падает

2022-11-21 16:05 UTC, randomroot commented on src/services/socketMiddleware.ts
> +                    socket.close(1000);
🔴 **Нужно исправить:**

Следует вынести "магическое число" в отдельную константу с названием, описывающий что хранится в значении, например здесь:

```js
const WS_NORMAL_CLOSE_CODE = 1000
```

2022-11-21 16:05 UTC, randomroot commented on src/pages/profile/orders.tsx
> +                                    .filter((item) => item !== undefined) as IIngredient[]
🟡 **Можно улучшить:**

Можно упростить код, если воспользоваться преимуществами автоматического преобразования `(undefined == false)`:

```js
order.ingredients.map(...).filter(Boolean)
```

2022-11-21 16:05 UTC, randomroot commented on src/services/actions/basket-slice.ts
> +    bun: {},
🔴 **Нужно исправить:**

В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2022-11-21 16:05 UTC, randomroot commented on src/services/actions/order-slice.ts
> +        console.log(' order: ', order);
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2022-11-21 16:05 UTC, randomroot commented on src/services/actions/register-slice.ts
> +        if (data.success !== true) {
🟡 **Можно улучшить:**

Можно упростить до `!data.success`

2022-11-22 08:10 UTC, buckster12 commented on src/components/feed-order-page/feed-order-page.tsx
> +        } else return () => {
Да, это понятно)) но тогда TS выдает ошибку что не хватает return:

`TS7030: Not all code paths return a value.`

либо можно отключить проверку через 
`
compilerOptions:{
  "noImplicitReturns": false
}
`
не знаю что лучше.) что посоветуете?

2022-11-22 08:29 UTC, randomroot commented on src/components/feed-order-page/feed-order-page.tsx
> +        } else return () => {
Само по себе правило полезное, но иногда чересчур дотошное. Поэтому, с учётом, что это единичный случай, можно оставить как есть. Если в проекте будет много подобного, то имеет смысл отключить, чтобы не плодить множество пустых функций (в качестве альтернативы можно вернуть `undefined` :) )

2022-11-23 08:54 UTC, buckster12 commented
постарался исправить все замечания по проекту.
Но не совсем понял про улучшение:

    Имеет смысл привести цвет прогресс-бара к дизайну, т.к. сейчас он темный и слабо различим на темном фоне проекта;

но ведь у меня совсем нет прогресс бара, насколько я помню :)
Уточните, пожалуйста, о чем речь?

2022-11-23 10:05 UTC, randomroot commented
> постарался исправить все замечания по проекту. Но не совсем понял про улучшение:
> 
> ```
> Имеет смысл привести цвет прогресс-бара к дизайну, т.к. сейчас он темный и слабо различим на темном фоне проекта;
> ```
> 
> но ведь у меня совсем нет прогресс бара, насколько я помню :) Уточните, пожалуйста, о чем речь?

Про прогресс бар, ошибся, прошу прощения, имелся ввиду скролл-бар

2022-11-23 20:06 UTC, randomroot requested changes
**Здравствуйте!**

Вы **отлично** доработали ваш проект, внесли множество корректировок и улучшений, в особенности для типизации, **так держать** 👍 

Однако, для успешного завершения работы, предлагаю вам рассмотреть следующие **важные** моменты и дополнить ваш проект еще одним рядом **корректировок**:

- В заказе вместо идентификаторов ингредиентов отправляются их полные объекты (см. https://disk.yandex.ru/i/IL0Ql5B_yWB6xg), следует преобразовать массивы и объекты булок в идентификаторы (метод и сейчас срабатывает, но возможно это недокументированная возможность API);
- Не следует убирать метод закрытие сокета из мидлвары, т.к. теперь сокеты не закрываются совсем (https://disk.yandex.ru/i/Z0prJDKEJG1w3Q). 
- В рамках прошлого ревью рассматривалась проблема одновременного вызова открытия и закрытия сокетов при переключении экранов. Самым простым и элегантным её решением может стать подключение 2-ух мидлвар: одну для ленты заказы, а вторую - для списка заказов, тогда переменная `socket` в каждом экземпляре будет уникальной и взаимное влияние исчезнет. При этом также необходимо будет для каждого сокета создать свой набор типов;

**Желаю вам хорошего дня!** 🐈 
_Если возникнут вопросы - оставляйте их в комментарии под ревью :)_

2022-11-23 20:06 UTC, randomroot commented on src/components/app-header/app-header.tsx
> +        if (
🔴 **Нужно исправить:**

**Здесь и далее по коду:** названия переменных следует привести к формату `camelCase`, за исключением названий компонентов Реакта и внешних констант.

2022-11-24 09:50 UTC, buckster12 commented
Никак не могу понять как сделать в socketMiddleware, чтобы он отрабатывал отдельно.
У меня получатся, что обе мидлвари подхватывают экшны и от AllOrders и от UserOrders и когда я перехожу с заказов юзера он все равно закрывает оба сокета.
Поскажите пожалуйста в какую сторону смотреть? Вроде создал разные типы:
```
export type TWsUserActions = {
    wsUserInit: typeof wsUserInit;
    wsUserClose: typeof wsUserClose;
    wsError: typeof wsError;
    wsOpen: typeof wsOpen;
    setOrders: typeof setOrders;
}

export type TWsActions = {
    wsAllInit: typeof wsAllInit,
    wsClose: typeof wsClose,
    setOrders: typeof setOrders,
    wsError: typeof wsError,
    wsOpen: typeof wsOpen
};
```
socket: 
`export const socketMiddleware = (wsActions: TWsActions | TWsUserActions): Middleware => {`

или мне нужно сделать два отдельных слайса?

2022-11-24 12:13 UTC, randomroot commented
@buckster12 
Добрый день! 
Да, всё верно сделайте два отдельных слайса - один для ленты заказов, а другой для истории заказов пользователя. 
И потом в миддлвари передавайте соответствующий набор экшенов:

```ts
      socketMiddleware(ordersWsActions),
      socketMiddleware(feedWsActions)
```

2022-11-24 18:21 UTC, buckster12 commented
доработал проект по замечаниям! :) 
протестировал, вроде теперь нигде ошибок нет, при переключении лент/сокетов.
+ убрал лишнюю информация при заказе, оставил только id ингредиентов
+ переименовал названия переменных которые нашел, где не нужна первая большая буква в названии

спасибо за замечания!

2022-11-25 07:53 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-05 12:32 UTC, merged